---
title: "Code Examples"
author: "herchu1"
date: "17 May 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code Examples

R Markdown see <http://rmarkdown.rstudio.com>.

Setup **code**:

```{r}
data("mtcars")
head(mtcars)
y = mtcars$mpg
x = cbind(1, mtcars$wt, mtcars$hp)
head(x)
```

### Least squares.

Fit with least squares.

$$ (x' * x)^{-1} * x' * y $$

```{r}
solve( t(x) %*% x ) %*% t(x) %*% y
```

R does the same using `lm`

```{r}
coef( lm( mpg ~ wt + hp, data=mtcars ))
```


### Mean centered

Given

$$ H = 1_n * (1_n' * 1_n)^{-1} * 1_n' $$
`H` is an `n x n` matrix of ones divided by n.

```{r}
n = nrow(x)
v1 = matrix(1, n)
H = v1 %*% solve(t(v1) %*% v1) %*% t(v1)
all( H == matrix(1, n, n) / n )
```

Centering `x` to the mean is

$$ (I - H) * x $$

```{r}
I = diag(1, n)
H = matrix(1, n, n) / n

xc = (I - H) %*% x
```

Testing the result. Take the mean of all columns (axis 2).
Using `sweep` can be faster.

```{r}
apply(xc, 2, mean)
xc2 = sweep(x, 2, apply(x, 2, mean))
```

### Variance

Using linear algebra and comparing it with bundled R function `var`.

$$ Variance = \frac{ x' * (I - H) * x }{n-1} $$

```{r}
vx = ( t(x) %*% (I - H) %*% x ) / (n-1)

round(vx, 6)
var(x)
```

